CC = g++
CC_FLAGS = -std=c++17 -pedantic -Wall -O2 -I./include
LD_LIBS = -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -static -static-libstdc++
# yum install glibc-static libstdc++-devel

EXEC = parun
SOURCES = $(wildcard src/*.cpp)
OBJECTS = $(SOURCES:.cpp=.o)

# Main target
$(EXEC): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(EXEC) $(LD_LIBS)

%.o: %.cpp
	$(CC) -c $(CC_FLAGS) $< -o $@

clean:
	rm -f $(EXEC) $(OBJECTS)
